/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Collaborator } from "./Collaborator";
import { CollaboratorCountArgs } from "./CollaboratorCountArgs";
import { CollaboratorFindManyArgs } from "./CollaboratorFindManyArgs";
import { CollaboratorFindUniqueArgs } from "./CollaboratorFindUniqueArgs";
import { CreateCollaboratorArgs } from "./CreateCollaboratorArgs";
import { UpdateCollaboratorArgs } from "./UpdateCollaboratorArgs";
import { DeleteCollaboratorArgs } from "./DeleteCollaboratorArgs";
import { SkillLevelFindManyArgs } from "../../skillLevel/base/SkillLevelFindManyArgs";
import { SkillLevel } from "../../skillLevel/base/SkillLevel";
import { CollaboratorService } from "../collaborator.service";
@graphql.Resolver(() => Collaborator)
export class CollaboratorResolverBase {
  constructor(protected readonly service: CollaboratorService) {}

  async _collaboratorsMeta(
    @graphql.Args() args: CollaboratorCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Collaborator])
  async collaborators(
    @graphql.Args() args: CollaboratorFindManyArgs
  ): Promise<Collaborator[]> {
    return this.service.collaborators(args);
  }

  @graphql.Query(() => Collaborator, { nullable: true })
  async collaborator(
    @graphql.Args() args: CollaboratorFindUniqueArgs
  ): Promise<Collaborator | null> {
    const result = await this.service.collaborator(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Collaborator)
  async createCollaborator(
    @graphql.Args() args: CreateCollaboratorArgs
  ): Promise<Collaborator> {
    return await this.service.createCollaborator({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Collaborator)
  async updateCollaborator(
    @graphql.Args() args: UpdateCollaboratorArgs
  ): Promise<Collaborator | null> {
    try {
      return await this.service.updateCollaborator({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Collaborator)
  async deleteCollaborator(
    @graphql.Args() args: DeleteCollaboratorArgs
  ): Promise<Collaborator | null> {
    try {
      return await this.service.deleteCollaborator(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [SkillLevel], { name: "skillLevels" })
  async findSkillLevels(
    @graphql.Parent() parent: Collaborator,
    @graphql.Args() args: SkillLevelFindManyArgs
  ): Promise<SkillLevel[]> {
    const results = await this.service.findSkillLevels(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
