/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TeamService } from "../team.service";
import { TeamCreateInput } from "./TeamCreateInput";
import { Team } from "./Team";
import { TeamFindManyArgs } from "./TeamFindManyArgs";
import { TeamWhereUniqueInput } from "./TeamWhereUniqueInput";
import { TeamUpdateInput } from "./TeamUpdateInput";
import { CollaboratorFindManyArgs } from "../../collaborator/base/CollaboratorFindManyArgs";
import { Collaborator } from "../../collaborator/base/Collaborator";
import { CollaboratorWhereUniqueInput } from "../../collaborator/base/CollaboratorWhereUniqueInput";
import { TeamSkillFindManyArgs } from "../../teamSkill/base/TeamSkillFindManyArgs";
import { TeamSkill } from "../../teamSkill/base/TeamSkill";
import { TeamSkillWhereUniqueInput } from "../../teamSkill/base/TeamSkillWhereUniqueInput";

export class TeamControllerBase {
  constructor(protected readonly service: TeamService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Team })
  async createTeam(@common.Body() data: TeamCreateInput): Promise<Team> {
    return await this.service.createTeam({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Team] })
  @ApiNestedQuery(TeamFindManyArgs)
  async teams(@common.Req() request: Request): Promise<Team[]> {
    const args = plainToClass(TeamFindManyArgs, request.query);
    return this.service.teams({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Team })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async team(
    @common.Param() params: TeamWhereUniqueInput
  ): Promise<Team | null> {
    const result = await this.service.team({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Team })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateTeam(
    @common.Param() params: TeamWhereUniqueInput,
    @common.Body() data: TeamUpdateInput
  ): Promise<Team | null> {
    try {
      return await this.service.updateTeam({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Team })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteTeam(
    @common.Param() params: TeamWhereUniqueInput
  ): Promise<Team | null> {
    try {
      return await this.service.deleteTeam({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/collaborators")
  @ApiNestedQuery(CollaboratorFindManyArgs)
  async findCollaborators(
    @common.Req() request: Request,
    @common.Param() params: TeamWhereUniqueInput
  ): Promise<Collaborator[]> {
    const query = plainToClass(CollaboratorFindManyArgs, request.query);
    const results = await this.service.findCollaborators(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        firstname: true,
        lastname: true,
        entrydate: true,
        position: true,
        birthdate: true,

        team: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/collaborators")
  async connectCollaborators(
    @common.Param() params: TeamWhereUniqueInput,
    @common.Body() body: CollaboratorWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      collaborators: {
        connect: body,
      },
    };
    await this.service.updateTeam({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/collaborators")
  async updateCollaborators(
    @common.Param() params: TeamWhereUniqueInput,
    @common.Body() body: CollaboratorWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      collaborators: {
        set: body,
      },
    };
    await this.service.updateTeam({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/collaborators")
  async disconnectCollaborators(
    @common.Param() params: TeamWhereUniqueInput,
    @common.Body() body: CollaboratorWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      collaborators: {
        disconnect: body,
      },
    };
    await this.service.updateTeam({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/teamSkills")
  @ApiNestedQuery(TeamSkillFindManyArgs)
  async findTeamSkills(
    @common.Req() request: Request,
    @common.Param() params: TeamWhereUniqueInput
  ): Promise<TeamSkill[]> {
    const query = plainToClass(TeamSkillFindManyArgs, request.query);
    const results = await this.service.findTeamSkills(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        skill: true,
        proficiency: true,

        team: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/teamSkills")
  async connectTeamSkills(
    @common.Param() params: TeamWhereUniqueInput,
    @common.Body() body: TeamSkillWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      teamSkills: {
        connect: body,
      },
    };
    await this.service.updateTeam({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/teamSkills")
  async updateTeamSkills(
    @common.Param() params: TeamWhereUniqueInput,
    @common.Body() body: TeamSkillWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      teamSkills: {
        set: body,
      },
    };
    await this.service.updateTeam({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/teamSkills")
  async disconnectTeamSkills(
    @common.Param() params: TeamWhereUniqueInput,
    @common.Body() body: TeamSkillWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      teamSkills: {
        disconnect: body,
      },
    };
    await this.service.updateTeam({
      where: params,
      data,
      select: { id: true },
    });
  }
}
